### ISSUE TITLE
Download URL from API is missing list length parameter 

### ISSUE THREAD

**Issue by apixipa** [DistriNet/tranco-list#11]
1. Insert YMD date like https://tranco-list.eu/api/lists/date/20220907

```
available	true
failed	false
download	"https://tranco-list.eu/download/7PVQX/"
```

2. Open https://tranco-list.eu/download/7PVQX/

404 Not Found

3. Why there is no `/lists/date/latest`, which will provide a very recent ZIP file? @eest

**Comment by VictorLeP** [comment]
- the `date` API endpoint now has a list length added to the `download` key
- `/download/{list_id}/` redirects to a URL with a list length, so now works
- `/lists/date/latest` is now a working API endpoint

Thanks for the suggestions!
