### ISSUE TITLE
Daily list for 2022-09-12 failed to generate

### ISSUE THREAD

**Issue by braedon** [DistriNet/tranco-list#13]
The latest list link on the website (https://tranco-list.eu/latest_list) shows an error, and the python package is throwing `AttributeError: The daily list for this date is currently unavailable.` when you try and fetch the latest list.

**Comment by VictorLeP** [comment]
Thanks for reporting, trying to generate the list again...

**Comment by VictorLeP** [comment]
The list is now online. Some other processes might still need to run/be started to propagate it to the other resources (API, BigQuery, ...)
