### ISSUE TITLE
API server gives 504 status code

### ISSUE THREAD

**Issue by rijswijk** [DistriNet/tranco-list#14]
Dear Tranco team,

Since a few days, the API server returns 504 status codes when attempting to access the server, e.g., the URL https://tranco-list.eu/api/lists/date/2022-09-12 to retrieve the list information for 2022-09-12.

And thank you for providing this service to the community!

**Comment by VictorLeP** [comment]
Should be fixed now! And thanks for the compliment :)

**Comment by rijswijk** [comment]
It was indeed fixed, but it seems to be back since yesterday :-/, would you have time to have another look?

**Comment by VictorLeP** [comment]
Back up :)

**Comment by rijswijk** [comment]
Indeed, it was, but now I get:
Failed to fetch https://tranco-list.eu/api/lists/date/2022-09-22 (status code 500)

(sorry 😬)

**Comment by VictorLeP** [comment]
And back up again (firewalls...)
