### ISSUE TITLE
Issues Downloading Full List

### ISSUE THREAD

**Issue by peterstory** [DistriNet/tranco-list#16]
Hello! I'm trying to download the full list for June 29th, 2022:
https://tranco-list.eu/list/Q9X24/1000000

I have no trouble downloading the top 1 million, but when I try to download the full list, I get a network error after 198MB have been downloaded. I've tried at least five times, always with the same result. Since I'm on-campus and have excellent internet speed, I don't think the issue is my connection. Perhaps there's some kind of server-side configuration error that is ending long-lived connections, thereby preventing the download of large files?

**Comment by mfrye** [comment]
We've been running into the same issue and have been trying on and off for the last few weeks. Cloudflare just returns a 502 bad gateway.

@VictorLeP can we discuss how to fix this? Tranco appears to be the best available post-Alexa option now. Maybe a direct S3 file transfer to save on transfer costs? Or maybe start charging for the full dump?

**Comment by VictorLeP** [comment]
We've changed the backend infrastructure, so full list downloads should be stable (they have been for a while now).
