### ISSUE TITLE
Creating CrUX filtered custom lists through the API

### ISSUE THREAD

**Issue by ghostwords** [DistriNet/tranco-list#18]
Hello and thank you for maintaining this wonderful service!

Is it possible to use the API to create custom lists limited to Chrome User Experience Report domains, potentially further filtered to a CrUX country, region or subregion?

Ideally all settings exposed on the [manual creation page](https://tranco-list.eu/configure) would also be [available to the API](https://tranco-list.eu/api_documentation#datatypes-configuration).

**Comment by ghostwords** [comment]
@VictorLeP A gentle ping! How does this request sound? Is this something that we could help with?

**Comment by VictorLeP** [comment]
The [API docs](https://tranco-list.eu/api_documentation#datatypes) have been updated with CrUX configuration parameters (`filterCRUX*`).
Let me know if anything is unclear for those parameters. I am also planning a feature that "exports" the equivalent API call for a selection made on the configuration page, but can't say yet when that will be done.

**Comment by ghostwords** [comment]
Will do and thank you!

**Comment by mschfh** [comment]
@VictorLeP
This [example list](https://tranco-list.eu/list/QWNX4/10000) shows the country filter on the website, but the values are missing from the [metadata](https://tranco-list.eu/api/lists/id/QWNX4) API response:

> `dataset for GB, and US (country)`

```json
{
	"list_id": "QWNX4",
	"available": true,
	"failed": false,
	"download": "https://tranco-list.eu/download/QWNX4/full",
	"created_on": "2025-05-24T07:51:31.871708",
	"configuration": {
		"filterCRUXType": "country",
		"filterPLD": "on",
		"filterCRUXMonth": "202504",
		"filterTLD": "false",
		"endDate": "2025-03-30",
		"filterCRUX": "on",
		"combinationMethod": "dowdall",
		"startDate": "2025-03-01",
		"listPrefix": "10000",
		"providers": [
			"majestic",
			"crux"
		]
	}
}
```


The `/lists/create` API returns a `400 Bad Request` when passing the `filterCRUXValue` parameter:

```json
{
	"providers": [
		"crux",
		"majestic"
	],
	"startDate": "2025-03-01",
	"endDate": "2025-03-31",
	"combinationMethod": "dowdall",
	"listPrefix": 10000,
	"filterPLD": "on",
	"filterTLD": "false",
	"filterCRUX": "on",
	"filterCRUXMonth": "latest",
	"filterCRUXType": "country",
	"filterCRUXValue": ["us", "gb"]
}
```

Is this a bug or is the request malformed?
