### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by meeeller** [DistriNet/tranco-list#2]
Love the concept of a Top 1 Million list hardened against manipulation.

Enjoy reading up on the methodologies and issues with creating this.

However, of a million sites on any day there seem to be alot of dead/parked sites overall, and even in high ranking traffic sites.

For Jul-20 I see 83k (8.3%) of sites that are not there.  Here are just a few high ranking examples:

* 8: windowsupdate.com
* 52: ytimg.com
* 105: wixsite.com
* 156: facebook.net
* 248: office.net
* mozilla.net

Any insight as to why this may be happening with freshly pulled rankings?

**Comment by VictorLeP** [comment]
Hello Matthew,
Thanks for the interest in Tranco!

In the default Tranco list, we reduce every domain to its "pay-level domain" ([which can be registered](https://publicsuffix.org/)), e.g. `i.ytimg.com` to `ytimg.com`. 
For the examples you give, there is a very popular _subdomain_ (e.g. [**i**.ytimg.com](https://i.ytimg.com/vi/tnGaCZZ5Z28/hqdefault.jpg)) that is reachable, even though its pay-level domain isn't. This is an artifact of the reduction to pay-level domains -- if you also want to keep the subdomains, you can use the [configuration tool](https://tranco-list.eu/configure) to disable the option to "Only include pay-level domains".
(Similarly, if a server were to be configured to only provide a valid response to specific URLs, crawling its root page may also lead to an 'unreachable' domain.)

Victor
