### ISSUE TITLE
Internal server error on https://tranco-list.eu/top-1m.csv.zip

### ISSUE THREAD

**Issue by ruurtjan** [DistriNet/tranco-list#21]
The latest top 1m list currently gives an internal server error:

https://tranco-list.eu/top-1m.csv.zip

![CleanShot 2024-01-25 at 13 16 29@2x](https://github.com/DistriNet/tranco-list/assets/1055478/8fb475b1-d0e5-4fc0-b644-dade3db8321f)

Edit: date specific lists too: https://tranco-list.eu/download_daily/4QGPX

**Comment by VictorLeP** [comment]
Temporary fix applied for top-1m.csv.zip. Maintenance is in progress anyway, the site might be unstable throughout the day.

**Comment by ruurtjan** [comment]
Thank you! And good luck with the maintenance :)

**Comment by VictorLeP** [comment]
> Thank you! And good luck with the maintenance :)

Thanks!
