### ISSUE TITLE
API endpoint for historic subdomain list

### ISSUE THREAD

**Issue by tillson** [DistriNet/tranco-list#23]
Hi,
I was hoping to download some historic subdomain lists, but noticed there is no easy API to grab the list ID at https://tranco-list.eu/api_documentation.  I was able to workaround by pulling the Location header from https://tranco-list.eu/daily_list?date=2024-04-03&subdomains=true, but an API endpoint would obviously provide better support.

**Comment by tillson** [comment]
Update: this already exists, but is undocumented: like on the rest of the website, add `?subdomains=True`

e.g., https://tranco-list.eu/api/lists/date/2024-01-01?subdomains=true

**Comment by VictorLeP** [comment]
Yes, I added the feature a while ago but forgot to update the API documentation.

The parameter is now mentioned on https://tranco-list.eu/api_documentation

Thanks for the notice!
