### ISSUE TITLE
 Daily list failed to generate

### ISSUE THREAD

**Issue by tallgaijin** [DistriNet/tranco-list#26]
Daily list failed to generate

Unfortunately, the daily list has failed to generate automatically and is currently unavailable. Please try again later.

Feel free to raise a [GitHub issue](https://github.com/DistriNet/tranco-list/issues). The following diagnostic information may help in debugging the issue:

list:None:None|subdomains:False|daily:2024-10-28

**Comment by VictorLeP** [comment]
Thanks for the report, the list has been generated now.
