### ISSUE TITLE
Not valid domain in the list

### ISSUE THREAD

**Issue by ramiloif** [DistriNet/tranco-list#3]
Hi, I have founs an invalid domain in tranco list (date 1/07/2021)

the domain is
`inner-active-.mobi`

![image](https://user-images.githubusercontent.com/15690633/124111394-e8fd3500-da71-11eb-9967-54a74e47e4d0.png)

**Comment by VictorLeP** [comment]
Hello,
Thanks for the notification.
The Tranco list is based on data from three providers (Alexa, Umbrella, Majestic). Umbrella's data happens to contain this invalid domain, which is a reflection of the fact that it is being actively queried, even though it will not resolve.
We do not filter these kinds of domains explicitly, as we want to transparently aggregate the source data without 'unannounced' processing (e.g., we do filter on pay-level domains, but that is explicitly stated on the list page).
If the presence of such invalid domains is an issue for your use case, I advise you to preprocess the list to remove such cases. However, for the moment, we will not consider removing them from the default list, as there might be use cases where such domains are still relevant.

**Comment by rabiori** [comment]
@VictorLeP can I ask a few questions regarding this?

1. Do you have any idea why a domain that is invalid and doesn't resolve get queried so much?
2. Can you give an example of a use case such a domain will be relevant?

**Comment by VictorLeP** [comment]
1) I'm guessing there is some misconfigured application somewhere where a dash was inadvertently added to the domain, and now all users of that app are trying to resolve it. In this case, `inner-active.mobi` (without the dash) appears to be a real service, so the source is probably somewhere in there.
2) Studying these kinds of misconfigurations could exactly be the use case: understanding how often these misconfigurations occur, or, if you are aware of such a misconfiguration, understanding how 'popular' the misconfigured site is.
