### ISSUE TITLE
Custom list failed to generated

### ISSUE THREAD

**Issue by mainzelM** [DistriNet/tranco-list#4]
I tried to configure and generate a custom list but got the error "List failed to generate". This happened to me twice (once today and once two days ago. 

The diagnostic information was "list:54PN:job_timeout".

Could you please have a look, what went wrong?

**Comment by VictorLeP** [comment]
Hi, thanks for the notification and including the diagnostics. They indicate that the list generation job timed out (>1 hour). This could be due to many/complex filters that cause the list generation process to exceed the allotted time.
What is the use case for your custom list? I could look into how to best create a list for that purpose.

**Comment by mainzelM** [comment]
Hi! Thanks for the reply, I wasn't aware that the list generation could be so time consuming...
My use case is to get a list of web sites that are popular for a European web user so I can scan these sites for trackers using DuckDuckGo's tracker radar. In your standard list, I found several entries that seemed outdated, so I thought I'd give the custom configuration a try... I'm also only interested in the top 20k entries.

**Comment by VictorLeP** [comment]
I have increased the job timeout, could you try again to see whether it succeeds now?
(FYI: it doesn't matter whether you select the top 20k entries - in order to sort the domains, a score has to be calculated for every domain anyway, so this will not decrease the computation time)

**Comment by mainzelM** [comment]
I gave it another try a couple of days ago but it still failed. I think, I'll do some filtering on the full list. Thanks for your support!
