### ISSUE TITLE
Plans after Alexa.com dies on 2022-05-01

### ISSUE THREAD

**Issue by pspacek** [DistriNet/tranco-list#6]
Hello,

FYI alexa.com is scheduled for end-of-life as of May 1st 2022:
https://support.alexa.com/hc/en-us/articles/4410503838999

I did not find a note about that in News section, so I wonder what are your plans for data sources after the EOL date?

Thank you for your work on Tranco list!

**Comment by VictorLeP** [comment]
We are aware that the Alexa list will be deprecated.
We plan to continue maintaining Tranco, and we're currently working on the next steps, including data sources. We'll communicate more about it in due time.
