### ISSUE TITLE
api now working

### ISSUE THREAD

**Issue by JohnAl1** [DistriNet/tranco-list#8]
Hi, 
I am trying to download tranco list using the api (GET on https://tranco-list.eu/api/ranks/domain/google.com or
GET on https://tranco-list.eu/api/lists/date/2022-05-17) but receiving 504.
Thanks in advance

**Comment by Nickolia** [comment]
We get 504 too

**Comment by Ilia-Sidorenko** [comment]
Hello there. 
All API related services seems to be down.
For example, GET request on https://tranco-list.eu/api/ranks/domain/tranco-list.eu URL has 504 response code.

I discovered first API issues 4 days ago - May 16, 2022

**Comment by hmfarooq** [comment]
HI, I got the same error API is not working. 
For example, I have hit the https://tranco-list.eu/api/ranks/domain/businessinsider.com and got 504 Gateway timeout host error.
Thanks

**Comment by VictorLeP** [comment]
The API is back up again.

**Comment by Nickolia** [comment]
Api not working again (

**Comment by VictorLeP** [comment]
> Api not working again (

It should be back now.

**Comment by Nickolia** [comment]
Again (

**Comment by VictorLeP** [comment]
> Again (

It should be back now.

**Comment by decoyduck** [comment]
Again (
